
services:
  ## --- MongoDB ---
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=testdb
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db
      - ./initdb.js:/docker-entrypoint-initdb.d/initdb.js
    networks:
      - socialmedia

  ## --- Spring Boot App ---
  app:
    build: .
    container_name: SocialMedia-app
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - logstash
    networks:
      - socialmedia

  ## --- Elasticsearch ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - socialmedia

  ## --- Logstash ---
  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - socialmedia

  ## --- Kibana ---
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - socialmedia

  ## --- Filebeat ---
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.4
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/app/logs
    depends_on:
      - logstash
    networks:
      - socialmedia

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - socialmedia

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - socialmedia
    depends_on:
      - prometheus

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - "9216:9216"
    networks:
      - socialmedia
    depends_on:
      - mongodb

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - socialmedia

networks:
  socialmedia:
    driver: bridge

volumes:
  mongodb_data:
