global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8080']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
